# Generated by Django 4.2 on 2023-04-18 21:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('featured_image', models.ImageField(height_field='height', upload_to='files', verbose_name='Imagen destacada', width_field='width')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última edición')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('name', models.CharField(max_length=150, verbose_name='Título')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('featured_image', models.ImageField(height_field='height', upload_to='files', verbose_name='Imagen destacada', width_field='width')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última edición')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorymodel', verbose_name='Categoría')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
