# Generated by Django 4.2 on 2023-04-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categorymodel_options_alter_postmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='seo_title',
            field=models.CharField(default='', max_length=150, verbose_name='Título SEO'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='seo_title',
            field=models.CharField(default='', max_length=150, verbose_name='Título SEO'),
        ),
    ]
