# Generated by Django 4.2 on 2023-04-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categorymodel_seo_title_postmodel_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='featured_image',
            field=models.ImageField(upload_to='files', verbose_name='Imagen destacada'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='featured_image',
            field=models.ImageField(upload_to='files', verbose_name='Imagen destacada'),
        ),
    ]
