# Generated by Django 4.2 on 2023-04-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_postmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Texto')),
                ('url', models.CharField(max_length=50, verbose_name='URL')),
                ('order', models.IntegerField(unique=True, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Enlace del menú',
                'verbose_name_plural': 'Enlaces del menú',
            },
        ),
    ]
