# Generated by Django 4.2 on 2023-04-22 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_image_alter_categorymodel_featured_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
