# Generated by Django 4.2 on 2023-04-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_categorymodel_options_alter_imagemodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidemodel',
            old_name='featured_image',
            new_name='image',
        ),
    ]
