# Generated by Django 4.2 on 2023-04-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_rename_featured_image_slidemodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="height",
            field=models.IntegerField(blank=True, null=True, verbose_name="Altura"),
        ),
        migrations.AddField(
            model_name="imagemodel",
            name="width",
            field=models.IntegerField(blank=True, null=True, verbose_name="Ancho"),
        ),
    ]
